import { Html, Head, Main, NextScript } from 'next/document';

export default function Document() {
  return (
    <Html lang="en">
      <Head>
        <meta name="description" content="Generated by create next agent" />
        <link rel="icon" href="/favicon.ico" />
        <script async src="https://cdn.tailwindcss.com"></script>
      </Head>

      <body className="bg-stone-700">
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}
